In [1]:
from __future__ import print_function, division

import plotly.graph_objects as go
import numpy as np
import scipy.spatial.distance
import math
import random
#from source.utils import *

import os
import torch
import pandas as pd
from skimage import io, transform
import numpy as np
import matplotlib.pyplot as plt
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms, utils
from torch.utils.data.dataset import random_split

In [2]:
import random

def read_pts(file):
    verts = np.genfromtxt(file)
    #return utils.cent_norm(verts)
    return verts

def read_seg(file):
    verts = np.genfromtxt(file, dtype= (int))
    return verts

def sample_2000(pts, pts_cat):    
    res1 = np.concatenate((pts,np.reshape(pts_cat, (pts_cat.shape[0], 1))), axis= 1)
    res = np.asarray(random.choices(res1, weights=None, cum_weights=None, k=2000))
    images = res[:, 0:3]
    categories = res[:, 3]
    categories-=np.ones(categories.shape)
    return images, categories
    
def Normalize(pointcloud):
    norm_pointcloud = pointcloud - np.mean(pointcloud, axis=0)
    norm_pointcloud /= np.max(np.linalg.norm(norm_pointcloud, axis=1))

    return  norm_pointcloud

In [3]:
root_dir = '/home/trojan/skia_projects/3d_facial_segmentation/part_segmentation/pointnet/pointnet'
files = []
valid = False

In [4]:
newdir = root_dir + '/datasets/airplane_part_seg/02691156/expert_verified/points_label/'

In [5]:
for file in os.listdir(newdir):
    o = {}
    o['category'] = newdir + file
    o['img_path'] = root_dir + '/datasets/airplane_part_seg/02691156/points/'+ file.replace('.seg', '.pts')
    files.append(o)

In [6]:
print(files)

[{'category': '/home/trojan/skia_projects/3d_facial_segmentation/part_segmentation/pointnet/pointnet/datasets/airplane_part_seg/02691156/expert_verified/points_label/c1e6d2235406d250e9ca68dea406967d.seg', 'img_path': '/home/trojan/skia_projects/3d_facial_segmentation/part_segmentation/pointnet/pointnet/datasets/airplane_part_seg/02691156/points/c1e6d2235406d250e9ca68dea406967d.pts'}, {'category': '/home/trojan/skia_projects/3d_facial_segmentation/part_segmentation/pointnet/pointnet/datasets/airplane_part_seg/02691156/expert_verified/points_label/48996e27f430ce286f67a5681eaf4d9f.seg', 'img_path': '/home/trojan/skia_projects/3d_facial_segmentation/part_segmentation/pointnet/pointnet/datasets/airplane_part_seg/02691156/points/48996e27f430ce286f67a5681eaf4d9f.pts'}, {'category': '/home/trojan/skia_projects/3d_facial_segmentation/part_segmentation/pointnet/pointnet/datasets/airplane_part_seg/02691156/expert_verified/points_label/17ad3ab1b1d12a7db26dc8ec64d633df.seg', 'img_path': '/home/troj

In [7]:
idx = 0

img_path = files[idx]['img_path']
category = files[idx]['category']

with open(img_path, 'r') as f:
    image1 = read_pts(f)
with open(category, 'r') as f:  
    category1 = read_seg(f)

In [8]:
print(image1)

[[ 0.20926 -0.00869  0.02061]
 [ 0.14734 -0.0506   0.02962]
 [ 0.17791 -0.04892  0.03027]
 ...
 [-0.04326 -0.0371   0.00759]
 [-0.28716 -0.0371   0.00693]
 [-0.14578 -0.0371   0.00694]]


In [9]:
print(category1)

[1 1 1 ... 1 1 1]


In [10]:
print(image1.dtype, category1.dtype)

float64 int64


In [11]:
image2, category2 = sample_2000(image1, category1)

In [12]:
print(len(image1), len(image2))

2565 2000


In [13]:
print(image2)

[[ 0.36295 -0.03183  0.01586]
 [-0.06119 -0.05086  0.14196]
 [ 0.11385 -0.00838  0.02023]
 ...
 [-0.32018  0.03247 -0.00758]
 [-0.32518  0.07384  0.00116]
 [-0.00076 -0.07027 -0.00756]]


In [14]:
image2 = Normalize(image2)

In [15]:
print(image2)

[[ 0.90965122 -0.00627872  0.03675154]
 [-0.09263827 -0.05124871  0.33473971]
 [ 0.32100051  0.04913621  0.04707833]
 ...
 [-0.70466014  0.14566925 -0.01863976]
 [-0.71647569  0.24343111  0.00201382]
 [ 0.05016447 -0.09711667 -0.0185925 ]]
